- .github/workflows/vercel-preview-deploy.yml
- src/components/ui/button.tsx
* close #14
* 기본 버튼(medium, large), 임시저장 버튼 개발
``` javascript
<Button variant="default" size="md">
수정하기
</Button>
<Button variant="disabled" size="md">
박스 비우기
</Button>
<Button variant="default" size="lg">
선택 완료
</Button>
<Button variant="disabled" size="lg">
선물 채우러 가기
</Button>
<Button variant="ghost" size="sm">
임시저장
</Button>
<Button variant="ghost_disabled" size="sm">
임시저장
</Button>
```
링크랑 이미지 카드 제외한 기본 스타일의 버튼만 구현하여 일단 전달드립니다.. !
shadcn을 처음 사용해봐서,, 잘못 구현한 부분이 있으면 말씀주세요!
> [Feat] 버튼 컴포넌트 개발 #14

- src/components/Card.tsx
* tailwind 단위가 안먹혀서 px로 수정했습니다.
* width가 아래와 같이 부모에 맞춰서 줄어드는 현상이 있어 `min-w` 값 추가해줬습니다!
* card 컴포넌트에 cursor pointer 추가했구, main에서 card 컴포넌트 사용할 때 isActive가 필요하지 않을 것 같아서, 선택적 프로퍼티로 두고 active랑 hover 스타일만 일단 추가했습니다. !!
> fix: card width 줄어듬 방지

- src/app/constants/constants.ts
- src/components/gift-upload/CustomTextArea.tsx
- src/components/gift-upload/GiftBoxDrawer.tsx
- src/components/gift-upload/InputReason.tsx
- src/components/giftbag/GiftList.tsx
- src/components/giftbag/SelectedGiftBag.tsx
- src/layout/Header.tsx
- src/stores/gift-upload/useStore.ts
- src/stores/giftbag/useStore.ts
- src/types/giftbag/types.ts
* close #13
- ~~textarea 한글 이상하게 쳐지는거 수정~~
- ~~태그쪽 로직 수정~~
- ~~클릭 시 이유 보이는거 수정상태에서는 클릭 안해도 바로 보이게 하기~~
- ~~이유 tag, message 상수로 관리~~
- 이미지 업로드 보기
- ~~drawer 컴포넌트명 변경~~
- ~~drawer 닫기 제대로 동작하도록~~
- ~~툴팁 나오게 하기~~
- ~~보따리 색 변하지 않도록~~
- selectedBagImage 파일에서 hydrate state 만들어서 관리.
- zustand persist 관리
- client에서 hydration(데이터를 불러오기) 되기 전에 초기 상태인 index:0이 먼저 렌더링되면서 0번 index의 보따리가 잠깐 깜빡 하게 되는 상황이 발생.
⇒ 데이터 불러오는 동안에 스피너 만들어둠
💡 추후 선물 배달하고 나서 보따리 색 초기화해야 함
- ~~박스 비우기 시 drawer 내용 변경~~
- ~~선물 상세보기에서 이유 빈 스트링이면 이유 없다는 text 띄워주기~~
- ~~수정상태일 때 상단바 뒤로가기 누르면 수정과 관련한 persist state 바꿔줘야 함~~
* 손가락과 손목이 곧 부서지겠습니다.
> feat: 선물 보따리 만들기 플로우 로직 및 퍼블리싱

- src/api/giftbag/api.ts
- src/app/giftbag/add/page.tsx
- src/app/giftbag/delivery/step2.tsx
- src/components/giftbag/GiftList.tsx
- src/layout/Header.tsx
- src/types/giftbag/types.ts
* close #69 
* /giftbag/add -> 선물이 2개 이상일 때 임시저장 버튼이 나타납니다.
* **sessionStorage에 보따리 id가 없을 때** -> `보따리 생성 api`
- 보따리 생성 api response로 각 선물 박스마다 id를 주는데, 해당 id를 localStorage에 저장중인 giftBoxes의 각 선물 박스에 새로 넣어줌(보따리 업데이트 시 request body에 각 선물 박스의 id가 필요.)
* **sessionStorage에 보따리 id가 있을 때** -> `보따리 업데이트 api`
* giftbag/delivery?step=2에서, 버튼을 눌렀을 시 모든 localStorage에 저장되던 것들 초기화시킴. (상단 헤더의 돌아가기 버튼을 통해 이전 페이지로 갈 수 있기 때문에 초기화를 해당 페이지에서 진행합니다.) 주석을 달아놓았는데, 배달부 선택하기api 에서 사용하는 giftBagId 또한 해당 페이지에서 초기화시킵니다! 따라서 초기화 함수 (resetStore)를 실행시키기 전에 배달부 선택 api를 쏘시면 될 것 같아요!
* **임시저장 버튼, 선물 배달하러 가기 버튼 눌렀을 때 id 유무에 따라 보따리 생성 api / 보따리 업데이트 api를 연결해두었습니다.**
* api 요청하는 코드가 어떤건 훅이 있고. .. 어떤건 훅이 없고 그러는데 마음이 급해서......... 시간이 나면 리팩토링해야할 것 같습니다.
> feat: 보따리 생성 api 플로우 수정

- src/app/giftbag/list/[giftbagId]/page.tsx
- src/components/myGiftbag/MyCardList.tsx
- src/components/myGiftbag/MyGiftBagStatusChip.tsx
- src/hooks/api/useFillGift.ts
- src/hooks/api/useGiftDetail.ts
* close #91
* 내가만든보따리 목록 페이지 - 각 카드 chip에서 답변 완료가 아닌 보따리에도 읽음 여부 Indicator가 떠서 답변 완료된 보따리에만 적용되도록 수정하였습니다.
* 전반적인 통일성을 위해 `giftbagId` -> `giftBagId` 로 수정 
* alert -> toast
* 보따리 마저 채우기 api 연결
➡️ 현진님이 구현해놓으셨던 `resetStore`를 통해 저장되어 있는 임시 저장 값 초기화를 진행한 뒤, 이후 통신을 위한 `giftBagId`를 세션에 저장하고 api 통신을 진행합니다! 
> feat: 보따리 마저 채우기 api 연결

- src/app/giftbag/list/[giftbagId]/answer/page.tsx
- src/app/home/page.tsx
- src/components/gift-upload/GiftForm.tsx
* 보따리 결과 페이지에서 화살표 버튼에 `hover:opacity-70`을 추가했습니다.
* home 화면이 렌더링되면 selectedGiftBagIndex (보따리 색 구분을 위함), giftBagName (보따리 이름), giftBoxes(선물상자들)을 초기화합니다.
* 선물 상세 입력 페이지에서 이미지, 이름 미입력 시 에러메세지를 띄우는 것이 아닌, 버튼 disabled로 변경했습니다.
> feat: 로컬스토리지에 저장해둔 것들 초기화

- src/components/giftbag/GiftList.tsx
- close #109 
- 선물 보따리 채우기 화면 첫 렌더링 시 툴팁이 자동으로 나오고, 유지 시간은 3초로 해두었습니다.
- 영상에서 브라우저 상단이 안보여서,, 마지막쯤에 새로고침을 해도 툴팁이 안나오는 것까지 확인했습니다
https://github.com/user-attachments/assets/49041e8b-1bfd-4ac7-ae4e-b686511185bf
> feat: 툴팁 나오는 타이밍 수정

- package-lock.json
- package.json
- src/app/giftbag/[id]/step2.tsx
- src/components/gift-upload/ImageCard.tsx
- src/components/gift-upload/SortableImageWrapper.tsx
- src/components/gift-upload/UploadImageList.tsx
- src/components/giftbag/GiftList.tsx
- src/types/components/types.ts
- close #108 
- dnd-kit 라이브러리를 설치했습니다. pull 받으신 후 npm i 해주세요!
- dnd-kit 라이브러리를 활용해 사진 순서를 drag and drop해 바꾸는 기능을 추가하였습니다. 이에 따라 대표사진도 바뀌게 됩니다. (동영상으로 기록해두었는데 용량이 너무 커서 첨부가 불가합니다,,ㅎㅎ 확인해주세요)
- 0번이 아닌 1번 선물박스가 채워져있음에도 불구하고 툴팁이 나와서 이 부분 수정했습니다. (채워진 선물박스가 0개라면 화면 렌더링 시 툴팁 띄움)
- 답변 전송 api 요청 실패 시 toast를 띄워두었습니다. api 에러 처리에 관련해서 어떻게 통일하면 좋을 지 프론트엔드 회의가 필요할 것 같아요.
- shadcn에서 기본적으로 제공하는 스켈레톤ui가 있는데 이 부분 전체 회의에서 말해보면 좋을 것 같아요
- 나머지 이슈들은 디자이너분들의 화면 수정 후 이루어져야할 것 같습니다.
> feat: 선물 사진 순서 바꾸기 기능 구현

- src/app/layout.tsx
- close #104
- PC 로컬 IP주소를 통해 모바일 환경에서 로컬 테스트 하였습니다. `http://<PC의 로컬 IP>:3000`
- 모바일 safari 환경에서 스크롤이 생겨 버튼이 안보이는 현상 해결했습니다.
- `vh` 단위는 전체 뷰포트 높이를 기준으로 하는데, 하단 주소창, 툴바 등의 UI 요소들을 viewport의 일부로 인식하여 기존 문제가 발생했습니다. 따라서, 실제로 화면에 보이는 영역을 기준으로 하는 `svh` (small viewport height) 단위로 변경하여 주소창이나 툴바 등을 제외한 공간을 기준으로 뷰포트 높이를 계산하여 문제를 해결할 수 있었습니다. (추가로 `min-h-screen`을 제거하였습니다.)
<div style="display: flex">
</div>
> design: mobile safari 호환성을 위해 100vh에서 100svh로 변경

- src/components/gift-upload/GiftForm.tsx
- close #128 
- 이미지가 하나도 채워져있지 않을 때 -> 텍스트가 보입니다.
<br/>
<br/>
- 이미지를 1개 이상 채웠을 때
> feat: 이미지 개수 관련 메세지 text 띄우기

- src/components/gift-upload/GiftForm.tsx
- src/components/gift-upload/SortableImageWrapper.tsx
- src/components/gift-upload/UploadImageList.tsx
- src/constants/constants.ts
- close #118 
- 이미지 용량 제한 및 개수와 관련한 text를 구현했습니다.
- (폰트색상) 이미지 0개: symantic-negative / 이미지 1개 이상: gray-300
<br/>
<br/>
- 10mb를 초과한 이미지를 업로드했을 경우, alert이 뜨도록 처리했습니다. (토스트는 유저 행동의 실패/성공 결과를 알려주거나 api 실패를 알려주는 것으로, 이미지 용량 제한과는 결이 살짝 다르다고 생각해서 alert으로 했는데 경고 토스트가 나을 것 같으면 말씀해주세요)
<br/>
<br/>
- 이미지 순서 바꾸기를 하면서 화면 밖으로 이미지들이 튀어나가서 이 부분 수정했습니다. 영상처럼 이미지를 업로드하는 부분은 스크롤이 안되게 하는거 괜찮을까요? 이전에는 그냥 저 부분이 전부 스크롤되어서 이미지를 업로드하는 부분까지 전체가 스크롤이 되고있었습니다.
https://github.com/user-attachments/assets/4c1b0024-4476-47d3-8b84-39572891334b
> feat: 선물 박스 채우기 - 이미지 용량 제한 추가

- src/app/bundle/add/page.tsx
- src/components/bundle/GiftList.tsx
- src/components/gift-upload/GiftForm.tsx
- src/stores/gift-upload/useStore.ts
- close #148 
- 선물 박스 삭제 시 사진과 같은 토스트가 띄워집니다.
<br/>
<br/>
- 선물 박스 수정 시 사진과 같은 토스트가 띄워집니다.
<br/>
<br/>
- toast같은 경우는 디자이너분들이 디자인을 새로 해주실지 아니면 shadcn을 쓸 지 고민해보신다고 하셨는데, 미리 일단 shadcn 토스트로 구현해두었습니다!
- 혹시 텍스트가 어색하다고 느끼신다면 추천받와요..
> feat: 선물 박스 삭제/수정 시 토스트 띄우기

- src/layout/Header.tsx
- 갑자기 발견한 이슈
- 수정 전: 스크롤이 있는 화면에서 image card의 x 버튼이 header보다 위로 올라오게 됩니다.
<br/>
<br/>
- 수정 후: header의 z-index를 전부 20으로 해두었습니다! (image card의 x 버튼 `z-index:10`)
> style: 헤더 z-index 수정

- src/app/my-bundles/[bundleId]/page.tsx
- src/queries/useDraftBundleGiftsQuery.ts
- 병합하다가 빠진 로직 수정 (답변이 완료된 보따리에만 답변 확인하기 버튼 보이도록)
- 내가 만든 보따리 상세 페이지에서 마저 채우기 버튼 클릭 시에 불러오는 임시 저장된 보따리 데이터를 상세 페이지 진입 시 자동으로 불러오고 있어서 상세 페이지 진입 시 계속 401 에러가 났습니다. (답변 대기, 답변 완료에도 임시 저장된 보따리를 fetch하려고 해서) 따라서, 임시 저장된 보따리의 경우에서 마저 채우기 버튼 클릭 시에만 불러오도록 수동으로 fetch 하는 로직으로 수정하였습니다.
> fix: 내가 만든 보따리 상세 페이지 로직 수정

- src/app/auth/login/page.tsx
- src/app/home/page.tsx
- src/components/bundle/GiftList.tsx
- src/components/bundle/SelectedBundle.tsx
- src/components/common/Card.tsx
- src/components/common/Icon.tsx
- src/components/common/Onboarding.tsx
> ...was detected as the Largest Contentful Paint (LCP). Please add the "priority" property if this image is above the fold.
- 초기 렌더에서 사용자에게 가장 크게 보이는 요소라서, Next.js가 이걸 LCP 요소로 인식하는데,  `priority` 속성이 빠져있어 위 경고가 떴습니다. `priority` 속성을 추가하였습니다.
> ....has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
- Image가 내부적으로 비율을 정확히 못 맞춘다고 판단하여 위 경고를 띄웠습니다. `height`를 `auto`로 명시하였습니다.
> fix: Image 태그 관련 warning 해결

- src/api/axiosInstance.ts
- close #76
- API 요청할 때, accessToken이 만료되어 401 Unauthorized을 받은 경우, 이때 interceptor가 동작하여 refreshToken을 통해 accessToken과 refreshToken을 재발급하여 재요청할 수 있도록 했습니다.
- 위 재발급 요청에서도 refreshToken이 만료되면 자동으로 `deleteToken`을 통해 로그아웃 되고, `/auth/login`으로 이동하도록 구현해두었습니다. 
- 가끔 처음에? 카카오 로그인 하자마자 setToken으로 accessToken이랑 refreshToken 저장하는데도, `/home`에서 보따리 프리뷰 데이터 불러오려고 하면 refreshToken이 없다고 떠서 로그아웃 처리가 되더라고요 🤔🥹
- 가끔 API 요청할 때마다 accessToken이 만료됐다고 떠서 재발급을 받게 되는데 이거는 accessToken이 길어지면 문제가 없을 것으로 예상..합니다
- console.log는 추후 계속해서 테스트가 필요할 것 같아서 일단 제거하지 않겠습니다!
> feat: accessToken 재발급 로직 및 자동 로그아웃

- src/app/bundle/[id]/page.tsx
- src/app/bundle/[id]/step2.tsx
- src/components/bundle/CarouselNavigator.tsx
- src/components/bundle/DetailGiftBox.tsx
- src/components/bundle/ReceiveAnswerChip.tsx
- src/types/bundle/types.ts
- close #182 
- 예전에 현상님께서 api res를 다시 snake case에서 camel case로 바꾸셨다고 했던 부분 수정하였습니다.
<br/>
<br/>
- 답변 페이지 레이아웃을 조금씩 바꾸었습니다. (margin, padding 값 같은)
- 해당 페이지에서의 header의 디자인을 수정했습니다. (불필요한 코드 정리)
<br/>
<br/>
- 웹 및 대부분의 모바일에서 보이는 화면
<br/>
<br/>
- 아이폰 se의 기종과 같이 화면이 작을 때 (선물이름에 배경이 회색인건 무시해주세요,, 마우스로 text 선택해놔서 그렇게 보이는거에요!!)
<br/>
<br/>
- 답변 완료 시 답변 태그 chip의 배경과 글씨 색을 바꾸어 자신이 선택했던 답변만 강조시켰습니다.
-> carousel navigation (현재 케러셀 페이지를 나타내주는 상단 점들)이 피그마에서는 헤더에 위치해있는데, 그렇게 되면 전달해줘야하는 props가 너무 복잡해져서 지금과 같이 헤더 밑에 위치해있어야 할 것 같아요. 
그래서 생각해본것: 사용자들이 해당 페이지에서 무엇을 해야하는지 잘 모르겠다고 말함 
=> 헤더에 사진과 같이 text를 넣어보았는데 이러면 조금 직관적인 것 같아서 어떻게 생각하세요? 회의에서도 말해봐야할 것 같아요.
> style: 답변 페이지 재퍼블리싱

- src/app/bundle/delivery/step2.tsx
- src/app/layout.tsx
- src/app/my-bundles/[bundleId]/page.tsx
- src/components/bundle/BundleForm.tsx
- src/hooks/useDynamicTitle.ts
- src/hooks/useResetStore.ts
- src/layout/GoToHomeDrawer.tsx
- src/layout/Header.tsx
- src/queries/useCreateBundleMutation.ts
- src/stores/bundle/useStore.ts
- close #199
- 기존 보따리 생성할 때 쓰이던 `useBundleStore`를 통해 상세 페이지 접근 시 불러온 name을 전역 상태에 저장하여 상세 페이지 헤더에 보따리 이름을 표시합니다.
> feat: 상세 페이지 헤더에 보따리 이름 표시

- src/constants/constants.ts
- close #204 
- 내가 만든 보따리 목록 페이지와 헤더 표시 등의 이유로 보따리 네임 최대 길이가 너무 긴 것 같아서 20자에서 15자로 줄였습니다. 
> feat: 보따리 이름 최대 길이 값 수정

- src/components/bundle/add/DeleteBundleDrawer.tsx
- src/constants/constants.ts
- src/types/components/types.ts
- 테스트 중 선물 비우기 drawer 간격이 넓은 것 같아 피그마 참고하여 간격 수정하고, Drawer Close Icon 사이즈도 수정했습니다!
> style: 선물 비우기 drawer 간격 및 아이콘 사이즈 수정

- src/app/my-bundles/[bundleId]/page.tsx
- src/app/my-bundles/page.tsx
- src/hooks/useDynamicTitle.ts
- close #185 
- 답변 대기 중인 보따리의 상세 페이지 내 공유 섹션 (카카오톡, 링크) absolute를 통해 하단 고정하였습니다. [b7d4fa3](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/203/commits/b7d4fa3f3236178914d8f7a0e7b5344f43362bf2)
- `<></>` fragment가 key를 가지고 있지 않아서 생기는 warning을 해결하였습니다. f87dbe36f8cfbae04038b776db756271d06d2e74
- src 속성 undefined 방지하여 warning 해결하였습니다. a8eaa3c56197af5903a59d9130381a422e19670d
- `useDynamicTitle.tsx`에서 '내가 만든 보따리' 타이틀이 빠져있어 추가하였습니다. ed1b91975684d6de994db045e0a57a96228db74c
> style: 답변 대기 중인 보따리의 상세 페이지 내 공유 섹션 위치 하단 고정 및 자잘한 warning 해결

- src/components/myBundle/MyBundleCard.tsx
- src/layout/Header.tsx
- 내가만든보따리 목록 카드에서 보따리 이름 길이가 최대일 경우(15자) truncate로 처리하였습니다. 
- 상세 페이지에서는 보따리(최대15자)/선물(최대20자) 이름 전체가 표시되어야 할 것 같아서 max-w 속성을 삭제했습니다.
width 375px 기준입니다.
- 테스트하면서 발견했는데, 상세 페이지 -> 마저 채우기 버튼 클릭 -> 선물 이름 수정하고, 뒤로가기 시에 이미 임시저장되어있는 보따리니까 생성할때와 동일하게 홈으로 바로 이동하거나 마저 채우기 버튼을 누른 그 상세 페이지로 이동해야 하는데 수정하는 페이지가 뜨더라고요! 
- 선물 박스 채우기에서는 굳이 전체를 안보여줘도 될 것 같기도 하고.. 수정 아이콘때메 좁아보이긴 하네요! 어떻게 생각하시나요?
> style: 헤더에 title 풀네임 다 표시되도록 수정, 보따리 목록 카드에서는 말줄임 추가

- src/layout/Header.tsx
- <img width="1470" alt="image" src="https://github.com/user-attachments/assets/407b8494-3ddd-4164-9751-e4c96bad9be8" />
-> 첨부드린 사진대로 답변 선택하기 페이지의 헤더에 `답변 선택하기` 라는 text를 추가했습니다.
> [Style] 답변 선택 페이지 헤더 text 추가

- src/app/bundle/add/page.tsx
- src/app/bundle/delivery/step2.tsx
- src/app/bundle/step1.tsx
- src/app/bundle/step2.tsx
- src/app/my-bundles/[bundleId]/[giftId]/page.tsx
- src/app/my-bundles/[bundleId]/page.tsx
- src/app/my-bundles/page.tsx
- src/app/setting/account/page.tsx
- src/components/common/DeliveryCard.tsx
- src/components/common/ShareSection.tsx
- src/components/myBundle/CopyLinkButton.tsx
- src/components/myBundle/MyBundleCard.tsx
- src/components/myBundle/MyBundleStatusChip.tsx
- src/components/myBundle/MyCardList.tsx
- src/hooks/useDynamicTitle.ts
- src/layout/Header.tsx
- close #210 
- close #211 
- close #212 
- 보따리 삭제 drawer UI 수정
- 선물 상세 페이지 UI 수정
- 보따리 상세 페이지 스타일 단위 수정
- MyCardList 컴포넌트 size props에 따른 gap size 수정
- 임의 값 대신 Tailwind scale로 정규화
- 내가 만든 보따리 목록 페이지 - 카드 내 보따리 이름 영역 제한하여 특정 영역을 벗어날 시 truncate로 표시되도록 했습니다. [c39451f](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/209/commits/c39451f9893f03891e0e2952ad5fcd36bc0fb9c3)
- 회의에서 얘기 나누었던 내가 만든 보따리 목록 페이지에서 보따리를 삭제할 경우, 보따리 삭제 drawer에 "선택한" 텍스트를 추가했습니다. [bd3697d](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/209/commits/bd3697dd08b1bb6f1038359f20bbf67743aef52d)
- 보따리 채우기 페이지에서 헤더에 이름이 잘리지 않고 풀네임이 표시되도록 다시 수정했습니다.
- 보따리 생성 쪽 step1, step2 피그마에 맞춰 스타일 수정했습니다.
- 보따리 채우는 페이지 불필요한 div 제거하여 레이아웃 수정했습니다.
- 배달 페이지 step2의 height를 하단 버튼 제외하도록 수정하였습니다. 
- …
> style: 전반적인 스타일 수정

- src/components/common/ShareSection.tsx
- 이미지가 아닌 버튼을 클릭해도 응답 페이지로 연결될 수 있도록 `서비스 이용하러 가기` 버튼에서 `보따리 풀어보기` 버튼으로 수정하였습니다.
> feat: 카카오톡 공유하기 버튼 수정

- src/hooks/useDynamicTitle.ts
- 보따리 결과 페이지의 타이틀이 `내가 만든 보따리`로 되어 있어서 `보따리 결과`로 수정했습니다.
> feat: 보따리 결과 페이지의 title 변경

- src/components/bundle/ReceiveGiftList.tsx
- src/components/bundle/add/CustomTooltipArrow.tsx
- src/components/bundle/add/GiftList.tsx
- 테스트하다가 이걸 깜빡했다는 걸 깨닫고.. 급하게 구현해두었습니다!
- 선물 박스가 하나라도 채워져있으면 툴팁이 보이게 됩니다.
> feat: 보따리 채우기 페이지 - 툴팁이 사라지지 않도록 구현

- src/app/my-bundles/page.tsx
- 내가 만든 보따리 목록 페이지에서 만든 보따리가 없을 때 표시되는 버튼의 href를 수정했습니다. (`/bundle/select` -> `/bundle?step=1`)
> fix: 보따리 만들러 가기 버튼 link 수정

- src/utils/dateFormatter.ts
- 보따리를 방금 만들었는데도 home에서 어제라고 표시가 되더라구요! `new Date(isoDateString)`로 파싱할 때 UTC 기준으로 해석될 수 있는 ISO 문자열을 그대로 넣으면 시간 차이가 발생할 수 있다고 합니다. 따라서, 한국 시간(KST)을 기준으로 계산하기 위해 UTC 기준 시간에 9시간을 더해 KST 시간으로 변환하였습니다.
> fix: UTC → KST로 보정

- src/app/bundle/delivery/step3.tsx
- src/app/my-bundles/page.tsx
- src/layout/Header.tsx
- src/stores/bundle/useStore.ts
- close #222
- ~~params에 `hideClose`를 추가하여 로딩 페이지에서는 close 버튼이 표시되지 않도록 했습니다. 더 좋은 방식이 있을까요?!~~
- 로딩 상태를 전역으로 관리하여 Header에서 검증하는 것이 더 직관적이라고 생각하여 (추후 모든 로딩 상태일때는 뒤로가기나 close버튼 표시되지 않도록) 로딩 상태를 전역으로 관리하는 방식으로 수정하였습니다!
- 로딩 상태라면 back button도 비활성화되도록 했습니다.
> fix: 배달 준비 중 로딩 페이지에서 close 버튼 숨기기

- src/app/home/page.tsx
- src/app/my-bundles/[bundleId]/page.tsx
- src/app/my-bundles/page.tsx
- src/hooks/bundle/add/useHandleCreateBundleClick.ts
- src/hooks/useResetStore.ts
- src/hooks/useTempSaveBundle.ts
- src/layout/Header.tsx
- src/stores/bundle/useStore.ts
- 기존 `useIsClickedUpdateFilledButton ` 전역 상태를 제거하고, sessiontStorage 로 관리되고 있던 `bundleId`를 통해 임시 저장 상태를 감지하도록 변경했습니다.
- 새로운 전역 상태 `isCreating`를 추가하여 최초 생성 상태와 임시 저장 상태를 구분하고, 뒤로가기 버튼 동작을 수정했습니다. `isCreating`이 true이고 `bundleId`가 존재하는 경우 `/home`으로 이동하고, `isCreating`이 false이며 `bundleId`가 존재하는 경우 상세 페이지(`/my-bundles/{bundleId}`)로 이동합니다.
- `보따리 만들러 가기` 버튼 동작을 처리하기 위해 `useHandleCreateBundleClick.ts` 훅을 새로 작성했습니다. 이 버튼은 홈 화면 또는 내가 만든 보따리가 하나도 없을 때 노출되며, 클릭 시 `isCreating`을 true로 설정하고 `/bundle?step=1`로 이동합니다.
- `마저 채우기` 버튼을 클릭하는 경우에는 `isCreating`을 false로 설정하여, 최초 생성이 아님을 명시합니다.
-
> fix: 보따리 최초 생성 상태를 전역 상태로 관리

- .eslintrc.json
- src/api/bundle/api.ts
- src/api/gift-upload/api.ts
- src/api/kakao/api.ts
- src/api/my-bundle/api.ts
- src/app/layout.tsx
- src/components/bundle/DetailGiftBox.tsx
- src/components/bundle/SelectedBundle.tsx
- src/components/bundle/add/BundleDrawer.tsx
- src/components/bundle/add/GiftList.tsx
- src/components/bundle/add/GiftThumbnailList.tsx
- src/components/gift-upload/ChipList.tsx
- src/components/gift-upload/CustomTextArea.tsx
- src/components/gift-upload/GiftForm.tsx
- src/components/gift-upload/ImageCard.tsx
- src/components/gift-upload/InputLink.tsx
- src/components/gift-upload/InputReason.tsx
- src/components/gift-upload/UploadImageList.tsx
- src/components/myBundle/MyBundleCard.tsx
- src/queries/useMyBundleDetailQuery.ts
- src/types/bundle/types.ts
- close #254 
- 현재 보따리 상세 페이지의 `보따리 1 상세페이지 -> 목록으로 돌아감 -> 보따리 2 상세페이지 ` 과정에서 보따리 1의 정보가 아주 잠깐 보였다가 보따리2로 바뀌는 버그를 해결했습니다. 위쪽 동영상이 수정 전, 아래쪽 동영상이 수정 후(network 설정 fast 4g)입니다. 8ce70a70ab6646aa7ae95504fdd3753570fef894
https://github.com/user-attachments/assets/e16bc323-0075-4413-bc57-af8d2c8024fc
https://github.com/user-attachments/assets/f3509e21-0740-43bf-9b6d-e7903a9f6f30
<br/>
<br/>
- eslint import 설정 해두셨던게 적용이 안된 파일들이 있어 일괄적으로 적용처리했습니다! [fe9050d](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/255/commits/fe9050d86e5d534ffd3c980b13ee404b4ac482bd)
<br/>
<br/>
- open graph title, image, description 적용했습니다! [695475f](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/255/commits/695475f9cc9b4d49ab8b13031e34ebd57cb015ab)
- Please fill out …
> feat: open graph 구현

- src/app/layout.tsx
- close #252 
- font의 weight를 400~700만 사용하고 있어서 font-weight를 수정하여 불필요한 폰트 렌더링 리소스를 낭비하지 않고자 했습니다.
> refactor: font weight 수정
