dnd-side-project/dnd-12th-5-frontend

src/layout/Header.tsx

design: 타이틀 가운데 정렬

---

src/app/giftbag/list/page.tsx
src/components/myGiftbag/MyGiftBagStatusChip.tsx
src/layout/Header.tsx

fix: 편집/완료 버튼 선택 안되는 오류 수정 및 상세 페이지로 리다이렉트 로직 추가

---

src/components/myGiftbag/MyGiftBagStatusChip.tsx

design: 목록 내 status chip 컴포넌트에서 div 태그 -> span 태그로 변경

---

src/app/giftbag/add/page.tsx
src/app/giftbag/name/page.tsx
src/app/page.tsx
src/components/common/DeliveryCard.tsx
src/components/gift-upload/GiftBoxDrawer.tsx
src/components/gift-upload/GiftForm.tsx
src/components/giftbag/GiftBagForm.tsx
src/components/giftbag/GiftList.tsx
src/layout/Header.tsx

* 메인 그래픽을 눌렀을 때 보따리를 만들러 가는건지 잘 모르겠을 수도 있겠다는 생각이 들어 `hover:opacity-70`을 추가했는데 어떠세요?? 첨부드린 사진에 마우스 포인터가 안나와있지만 `hover` 되었을 때 입니다. 별로인 것 같으면 다시 원래대로 돌려놓겠습니당
* 마찬가지로 배달부 카드에도 hover:opacity-70 추가해두었습니다! (4번째 배달부 적용)
* ??? 빅토리가 누구죠...ㅋㅋㅋㅋㅋㅋㅋ 픽토리로 수정했습니다.;;
* 예전에 제가 첨부드린 화면에서 window.close()를 통해 현재 창을 닫는게 가능하다고 답변드린 적 있는데, 이 경우 window.open() 객체로 열린 창으로만 가능한 기능이라고 하네요...... 일단 헤더쪽에 주석처리해서 두긴 했는데, 현재는 저 화면에서 그냥 엑스버튼 없이만 헤더 해두었습니다.. 어떻게할까요?.?

refactor: 퍼블리싱 및 로직 확인 후 수정

---

src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
src/components/common/LinkButton.tsx
src/data/giftbagData.ts

* close #61
* 임시 데이터 추가해서 진행했습니다
* 저도 첨부한 링크 바로가기 버튼 hover 시에 opacity 추가해뒀습니다!
* 선물을 고른 이유를 작성하지 않았거나 링크가 첨부되지 않은 경우 disable 디자인 추가

design: 내가 담았던 선물 상세 페이지

---

src/components/gift-upload/CustomTextArea.tsx
src/components/gift-upload/GiftForm.tsx
src/components/gift-upload/UploadImageList.tsx
src/types/gift-upload/types.ts

* 이미지 업로드와 관련해 전체적으로 로직을 수정했습니다. 나쁜놈. ㅠㅠ 이제 버그 없겠죠? (제발)
* 선물을 선택한 이유의 textArea의 글자 크기를 수정했습니다! 너무 큰 것 같아서 (16px -> 14px)

fix: 이미지 업로드 관련 로직 수정

---

src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
src/app/giftbag/list/[giftbagId]/page.tsx
src/app/giftbag/list/page.tsx
src/hooks/api/useDeleteMyGiftBag.ts
src/hooks/api/useGiftDetail.ts
src/hooks/api/useMyGiftBagDetail.ts

* close #48
* close #86 
* close #49 
* 내가만든보따리 목록에서와 상세에서의 삭제 api 
* 내가만든보따리 상세 페이지 api
* 내가담았던선물 상세 페이지 api
* 서버에서 임시로 넣어둔 가짜 이미지 처리만 문제가 있는데, 실제 보따리 생성하고 나서 테스트해보면 될 것 같아요!

feat: 내가만든보따리 관련 api

---

src/app/giftbag/delivery/page.tsx
src/app/giftbag/delivery/step1.tsx
src/app/giftbag/delivery/step2.tsx
src/app/giftbag/delivery/step3.tsx
src/components/common/DeliveryCard.tsx
src/data/deliveryCharacterData.ts
src/hooks/api/useDeliveryGiftBag.ts
src/types/giftbag/types.ts

* close #89
* 배달부 설정 api 연결
* 링크 복사 기능 추가
* ``http://localhost:3000/giftbag/${link}`` 이 경로를 통해 사용자가 보따리를 풀어볼 수 있습니다! (추후 URL 변경 필요)
* 스타일 부분은 제외하고 일단 요거부터 전달드립니다!

Feat: 배달부 설정 api 연결, 링크 복사 기능

---

next.config.mjs
package-lock.json
package.json
src/api/giftbag/api.ts
src/app/giftbag/[id]/page.tsx
src/app/giftbag/[id]/step2.tsx
src/app/giftbag/delivery/step3.tsx
src/app/giftbag/list/[giftbagId]/page.tsx
src/app/setting/notice/page.tsx
src/app/setting/page.tsx
src/components/giftbag/ReceiveGiftList.tsx
src/components/ui/dialog.tsx
src/layout/Header.tsx

* close #92 
* close #71
* close #90 
* 설정쪽 관련해서 퍼블리싱 및 하드코딩 진행했습니다!
* 버전 정보
* 공지사항 - 헤더 매핑, 공지사항 하드코딩 (shadcn dialog로 구현했는데, 웹에서는 요상하지만 앱에서는 저렇게 괜찮은 비율로 나옵니다!)
* 보따리 풀어보기 api 연결했습니당.
* 배달부 step3 에서 링크 -> `/giftbag/${link} => /giftbag/${link}?step=1` 로 변경했습니다.
* 선물 상세보기 링크복사도 변경해두었습니다!

feat: 보따리 풀어보기 api 연결

---

src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx

* close #87
* 썸네일이 아닌 썸네일 제외한 imageUrls을 띄우고 있어서 정상 작동하지 않았습니다.
* 임시 데이터 제거
* 썸네일을 imageUrls 앞단에 추가하여 `combinedImages`로 캐러셀 되도록 수정
* `giftbagId` -> `giftBagId`

fix: 이미지 캐러셀 오류 수정

---

src/api/giftbag/api.ts
src/app/giftbag/[id]/page.tsx
src/app/giftbag/[id]/step2.tsx
src/app/giftbag/list/[giftbagId]/answer/page.tsx
src/app/setting/page.tsx
src/components/gift-upload/CustomTextArea.tsx
src/components/gift-upload/GiftForm.tsx
src/components/gift-upload/InputReason.tsx
src/components/giftbag/AnswerChip.tsx
src/constants/constants.ts
src/layout/Header.tsx
src/types/giftbag/types.ts
src/utils/utils.ts

* close #72 
* close #95 
* 보따리 풀어보기 - loading style 수정했습니다. (위치)
* 답변 저장 api를 연결했습니다.
* 보따리 결과 확인하기 api를 연결했습니다.
* 로그아웃 api 없이, 프론트에서 localStorage에 저장되어있는 accessToken, refreshToken을 삭제하는 방식으로 로그아웃을 구현했습니다.

feat: 답변 저장하기 api 연결

---

src/app/giftbag/add/page.tsx
src/app/giftbag/list/[giftbagId]/[giftId]/page.tsx
src/app/giftbag/list/[giftbagId]/page.tsx
src/app/giftbag/list/page.tsx
src/components/giftbag/GiftList.tsx
src/hooks/api/useFillGift.ts
src/layout/Header.tsx

Fix: 마저 채우기 관련 api 및 로직 오류

---

.eslintrc.json
src/app/giftbag/list/[giftBagId]/page.tsx
src/app/home/page.tsx
src/app/kakao/callback/page.tsx
src/components/gift-upload/GiftForm.tsx
src/components/ui/dialog.tsx
src/components/ui/textarea.tsx
src/components/ui/toast.tsx
src/components/ui/toaster.tsx
src/hooks/api/useDeliveryGiftBag.ts
src/lib/utils.ts

* eslintrc 파일을 수정했습니다.
* 요걸로 인해서 이전에 적용되지 않았던 prettier 설정이 다 적용되어서 반영하여 파일들 업데이트 해두었습니다!
* useEffect dependency array에 제대로 추가하지 않아 warning이 떴었는데, 이를 없애기 위해 dependency array 수정했습니다!
첨부드린 사진의 KAKAO_AUTH_URL 부분이나, tailwindcss 부분에서  prettier의 printWidth가 제대로 반영되지 않는다고 생각하고 있었는데요! 
요번에 이거 작업하면서 알아보니까 예를 들어 printWidth:80은 가능하면 80자를 기준으로 줄바꿈을 고려한다는 의미라고 합니다! 그리구 prettier는 " " 사이를 자동 줄바꿈하지 않는다구 하네요,,, 처음알았습니다

refactor: 예림님 피드백 1번 - eslintrc파일 수정

---

src/layout/Header.tsx

- close #122
- 배달 페이지 마지막 step에서 x 버튼 클릭 시 home으로 이동하도록 `Header.tsx` 파일 수정했습니다.

feat: 배달 페이지 내 x 버튼 클릭 시 home으로 이동

---

src/app/giftbag/list/[giftBagId]/page.tsx
src/app/giftbag/list/page.tsx
src/components/gift-upload/GiftBoxDrawer.tsx
src/components/ui/drawer.tsx
src/layout/GoToHomeDrawer.tsx
src/layout/Header.tsx

- close #112 
- close #113 
- 임시저장이 되어있지 않은 경우 뒤로가기를 누르면 drawer가 나오게 됩니다. 해당 drawer를 통해 사용자는 home으로 이동이 가능합니다.
https://github.com/user-attachments/assets/2df76812-7dcf-43b5-93df-a26f41cd1605
- 임시저장을 한 경우 뒤로가기를 누르면 home으로 이동합니다.
https://github.com/user-attachments/assets/e7e65ef7-5be8-4826-b5c2-d6b0cf4ae282
- 이전 shadcn의 drawer는 상단에 드래그를 해서 drawer를 없앨 수 있는 회색 부분이 있었는데 그 부분을 주석처리해두어 없앴습니다.
- shadcn drawer를 수정함에 따라 기존 drawer들의 title에 mt-3을 주어 조금 자연스러울 수 있도록 바꾸었습니다.

feat: 보따리 채우기 - 뒤로가기 관련 수정

---

src/app/bundle/add/page.tsx
src/constants/constants.ts
src/layout/Header.tsx

- close #133 
- constants -> MIN_GIFTBOX_AMOUNT=1 을 추가했습니다.
- 보따리 채우기 화면에서 상자를 하나 이상 채우면
1. 헤더의 임시 저장 버튼이 보입니다.
2. 배달하기 버튼이 활성화됩니다.

refactor: 선물 상자 최소 개수 수정

---

src/api/bundle/api.ts
src/app/bundle/[id]/step2.tsx
src/components/bundle/DetailGiftBox.tsx
src/components/bundle/ReceiveAnswerChip.tsx
src/components/bundle/ReceiveAnswerChipList.tsx
src/constants/constants.ts
src/layout/Header.tsx
src/types/bundle/types.ts

- close #156
- close #164 
- 답변 페이지 퍼블리싱을 진행했습니다.
https://github.com/user-attachments/assets/7079a586-5636-456a-a558-1b94539aaf8c
- /bundle/[id]/step=2에서, 답변 전송 api가 아닌 보따리 풀어보기 api를 요청하고 있어서 수정했습니다.
- 파일 내부에 api 코드가 있어서 api.ts 파일에 코드 분리를 진행했습니다.
- 답변 태그가 수정되어서 이 부분 수정했습니다.
(왼쪽: 이전 / 오른쪽:수정 후)

style: 답변 페이지 퍼블리싱

---

package-lock.json
package.json
src/api/api-url.ts
src/api/axiosInstance.ts
src/api/bundle/api.ts
src/api/gift-upload/api.ts
src/api/kakao/api.ts
src/app/bundle/[id]/page.tsx
src/app/bundle/[id]/step2.tsx
src/app/kakao/callback/page.tsx
src/components/bundle/DetailGiftBox.tsx
src/components/bundle/ReceiveAnswerChip.tsx
src/components/bundle/ReceiveAnswerChipList.tsx
src/constants/constants.ts
src/layout/Header.tsx
src/queries/kakao/useKakaoLogin.ts
src/queries/useBundlesPreviewQuery.ts
src/queries/useDeleteMyBundleMutation.ts
src/queries/useDraftBundleGiftsQuery.ts
src/types/bundle/types.ts
src/utils/axios.ts

- close #166
- axios instance를 생성했습니다.
- 기존 fetch 방식의 API 호출을 axios Instance 기반으로 교체했습니다.
- 현진님 올라와 있던 PR pull 받아서 api 통신 코드를 수정했습니다. (axios Instance 적용)
- 모든 API 호출에 `try-catch` 문을 적용하고, 공통 에러 핸들링 유틸 함수를 만들어 구체적인 에러 메세지를 띄우도록 했습니다. [deb3a5a](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/167/commits/deb3a5af476913a5195015abeccefc2a3051a617)
- 카카오 로그인 관련 API랑 tanstack query 훅을 분리하였습니다. [4875d71](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/167/commits/4875d71250c8eca8f4fef968229a0414ea999c8f)
- 내가 만든 보따리 삭제 후 목록이 업데이트 되지 않는 오류를 발견하고, query key `Bundles` -> `bundles`로 오타 수정했습니다. [f221538](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/167/commits/f2215386acabb6a75ad38aac4bb25362c53200d0)
- 상대방 답변 페이지에서 보따리를 정상적으로 불러오고 있지 못하는 오류를 발견하여 서버 필드명과 프론트 …

feat: Axios Instance 생성

---

src/api/bundle/api.ts
src/app/bundle/[id]/step2.tsx

- close #165 
- requestBody -> bundleId, gifts / query params -> link (보따리 uuid) 가 되도록 백엔드 수정에 따라 수정했습니다.

api: 답변 전송 api 수정

---

src/api/api-url.ts
src/api/bundle/api.ts
src/app/bundle/[id]/page.tsx
src/app/bundle/select/page.tsx
src/types/bundle/types.ts

- close #175 
- 이전에 accessToken을 필요로 했던 api 외의 선물 받는 사람 입장에서 자신이 답변한 내용을 확인할 수 있도록 api를 추가해 연결했습니다.
- dev에서 build error가 나는 것을 확인했는데 머지할 때 이상이 있었는 지 CardList를 두 번 import해오고 있어서 그 부분 삭제했습니다.

api: 선물 받는 사람 보따리 결과 확인 api

---

src/components/gift-upload/GiftForm.tsx
src/components/gift-upload/UploadImageList.tsx
src/components/ui/toast.tsx
src/constants/constants.ts
src/queries/useUploadImageMutation.ts
src/types/components/types.ts

- close #183 
- 이미지 업로드 mutation을 custom hook으로 분리하였습니다.
- 이미지 저장 시 로직이 꼬여있어 코드를 수정했습니다.
- 이미지를 서버에 업로드하는 것을 실패했을 시, 토스트가 띄워지게됩니다.
https://github.com/user-attachments/assets/9456d7a8-83ba-485e-94f8-c8bcefee8d4b

bug: 선물 박스 채우기 - 이미지 업로드 버그 수정

---

src/app/bundle/delivery/step3.tsx
tailwind.config.ts

- close #144
- 슬랙 참고하여 배달 페이지 step3 화면 (링크 복사 및 공유) 전에 로딩 화면 추가했습니다.
- 3초로 해두었습니다.
https://github.com/user-attachments/assets/06d76a86-e045-4ece-ae98-ca143ed2dedd

feat: 배달 페이지 로딩 추가

---

src/api/api-url.ts
src/api/kakao/api.ts
src/app/setting/account/page.tsx
src/queries/useDeleteUserMutation.ts

- close #228 
- 회원 탈퇴 기능을 구현하였습니다.

feat: 회원 탈퇴 기능

---

src/app/bundle/[id]/step2.tsx

style: 응답 페이지 scrollbar 숨기기

---

src/components/common/ErrorMessage.tsx
src/components/gift-upload/GiftForm.tsx
src/components/gift-upload/ImageCard.tsx
src/utils/giftBoxUtils.ts

- 선물 박스를 채울 때 링크 유효성 검사를 추가했습니다.
https://github.com/user-attachments/assets/3fc31574-9030-4083-9a13-8ad05d08c068
- 선물 박스를 채울 때 이미지 업로드하는 부분의 x 아이콘 관련 스타일 수정을 예전 pr에서 해두었는데, 머지되는 과정에서 누락되었나봐요(??..) 똑같이 다시 구현해서 제대로 아이콘이 짤리지 않고 보이도록 수정했습니다. [12a9f5c](https://github.com/dnd-side-project/dnd-12th-5-frontend/pull/240/commits/12a9f5c7d1a3f653136eee63b1434a302d5bca16)

feat: 선물 박스 채우기 - 링크 유효성검사 추가
